[package]
name = "mstickereditor"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
serde     = { version = "1.0", features = ["derive"] }
toml      = "0.5.8"
attohttpc = { version = "0.18", features = ["compress", "json", "rustls"], default-features = false }
anyhow    = "1.0"
